DROP TABLE IF EXISTS INGREDIENT;
DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS RECIPE_INGREDIENT;

CREATE TABLE INGREDIENT (
    IID                     IDENTITY PRIMARY KEY,
    CREATED_DATE            TIMESTAMP   NOT NULL,
    NAME                    VARCHAR(255) NOT NULL,
    HEALTH_BENEFIT          VARCHAR(255) NOT NULL
);

CREATE TABLE RECIPE (
    RID                     IDENTITY PRIMARY KEY,
    CREATED_DATE            TIMESTAMP   NOT NULL,
    NAME                    VARCHAR(255) NOT NULL,
    INSTRUCTIONS            VARCHAR(255) NOT NULL,
    SERVINGS                INT NOT NULL,
    VEGETARIAN              BOOLEAN NOT NULL
);

CREATE TABLE RECIPE_INGREDIENT (
    ID                      IDENTITY PRIMARY KEY,
    IID                     INTEGER NOT NULL,
    RID                     INTEGER NOT NULL,
    MEASURE                 DOUBLE NOT NULL,
    UNIT                    VARCHAR(20) NOT NULL,
    FOREIGN KEY (RID) REFERENCES RECIPE,
    FOREIGN KEY (IID) REFERENCES INGREDIENT
);