stages:
  - stage: ProvisionContinuesIntegration
    displayName: "Provision Continues Integration"
    pool:
      vmImage: windows-latest
    jobs:
      - job: ProvisionContinuesIntegration
        displayName: "Provision Continues Integration"
        steps:
          - task: Maven@3
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
          - task: CopyFiles@2
            displayName: 'Copy Files to artifact staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/target/*.?(war|jar)'
              TargetFolder: $(Build.ArtifactStagingDirectory)
          - upload: $(Build.ArtifactStagingDirectory)
            artifact: hello-world