# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none # none - run the infrastructure manually or branch name -> master

variables:
  - name: resourceGroup
    value: "recipe-rg"
  - name: servicePrincipal
    value: "recipe-sp"
  - name: location
    value: "westeurope"
  - name: appServicePlan
    value: "recipe-asp"
  - name: appService
    value: "recipe-app-service"
  - name: virtualNetwork
    value: "recipe-vnet"
  - name: virtualNetworkSubnet
    value: "recipe-subnet"
  - name: applicationInsights
    value: "recipe-appinsights"

stages:
  - template: pipelines/templates/recipe.infrastructure.yml
    parameters:
      resourceGroup: $(resourceGroup)
      servicePrincipal: $(servicePrincipal)
      location: $(location)
      appServicePlan: $(appServicePlan)
      appService: $(appService)
      virtualNetwork: $(virtualNetwork)
      virtualNetworkSubnet: $(virtualNetworkSubnet)
      applicationInsights: $(applicationInsights)